spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: micro-news
            uri: http://localhost:8081
            predicates:
              - Path=/news/**
          - id: micro-comments
            uri: http://localhost:8082
            predicates:
              - Path=/comments/**
          - id: micro-search
            uri: http://localhost:8083
            predicates:
              - Path=/search/**

comments-service:
  url:
    micro-comments:8082

news-service:
  url:
    micro-news:8081

search-service:
  url:
    micro-search:8083